# Generated by Django 3.1.5 on 2021-01-30 18:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=120, unique=True)),
                ('ProducImage', models.ImageField(upload_to=home.models.user_directory_path)),
                ('Price', models.FloatField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('AvalabelForSale', models.BooleanField(default=True)),
            ],
        ),
    ]
