# Generated by Django 3.1.5 on 2021-01-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_avalabelforsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Activate',
            field=models.BooleanField(default=True),
        ),
    ]
